name: Run Chartink Alerts

on:
  schedule:
    - cron: "*/15 * * * 1-5"  # Every 15 mins on weekdays (Mon–Fri)
  workflow_dispatch:

jobs:
  run-chartink-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore seen_stocks cache
        uses: actions/cache@v4
        with:
          path: seen_stocks.json
          key: seen-stocks-${{ github.run_id }}
          restore-keys: |
            seen-stocks-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alert script
        run: python Chartink_Multi_Scanner_Alert.py

      - name: Save seen_stocks.json to cache
        uses: actions/cache/save@v4
        with:
          path: seen_stocks.json
          key: seen-stocks-${{ github.run_id }}
